version: '2'

services:
  haproxy:
    image: haproxy
    ports:
      - "8123:8123"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - ch1
      - ch2
      - ch3
      - ch4

  zookeeper:
    image: zookeeper
    ports:
      - 2181:2181
  ch1:
    build:
      context: .
      dockerfile: Dockerfile.ch1
    depends_on:
      - zookeeper
    expose:
      - 8123
    ports:
      - 8811:8123
      - 9011:9000
    volumes:
      - "./clickhouse-cluster-data/volume1:/var/lib/clickhouse"
  ch2:
    build:
      context: .
      dockerfile: Dockerfile.ch2
    depends_on:
      - zookeeper
    expose:
      - 8123
    ports:
      - 8812:8123
      - 9012:9000
    volumes:
      - "./clickhouse-cluster-data/volume2:/var/lib/clickhouse"
  ch3:
    build:
      context: .
      dockerfile: Dockerfile.ch3
    depends_on:
      - zookeeper
    expose:
      - 8123
    ports:
      - 8813:8123
      - 9013:9000
    volumes:
      - "./clickhouse-cluster-data/volume3:/var/lib/clickhouse"
  ch4:
    build:
      context: .
      dockerfile: Dockerfile.ch4
    depends_on:
      - zookeeper
    expose:
      - 8123
    ports:
      - 8814:8123
      - 9014:9000
    volumes:
      - "./clickhouse-cluster-data/volume4:/var/lib/clickhouse"